"""first migration

Revision ID: bf72a90d96c0
Revises: 
Create Date: 2022-03-03 03:38:12.630420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf72a90d96c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rushing_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('att', sa.Integer(), nullable=False),
    sa.Column('att_g', sa.Float(), nullable=False),
    sa.Column('yds', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=False),
    sa.Column('yds_g', sa.Float(), nullable=False),
    sa.Column('td', sa.Integer(), nullable=False),
    sa.Column('lng', sa.String(), nullable=False),
    sa.Column('first', sa.Integer(), nullable=False),
    sa.Column('first_percent', sa.Float(), nullable=False),
    sa.Column('twenty_plus', sa.Integer(), nullable=False),
    sa.Column('forty_plus', sa.Integer(), nullable=False),
    sa.Column('fum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rushing_stats_id'), 'rushing_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rushing_stats_id'), table_name='rushing_stats')
    op.drop_table('rushing_stats')
    # ### end Alembic commands ###
