"""create 3nf models

Revision ID: d05beaf3ede4
Revises: 3b5eac7edd79
Create Date: 2022-03-06 19:10:03.103053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05beaf3ede4'
down_revision = '3b5eac7edd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('short_name')
    )
    op.create_index(op.f('ix_position_short_name'), 'position', ['short_name'], unique=False)
    op.create_table('team',
    sa.Column('short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('short_name')
    )
    op.create_index(op.f('ix_team_short_name'), 'team', ['short_name'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.short_name'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.short_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('rushing_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('att', sa.Integer(), nullable=True),
    sa.Column('att_g', sa.Float(), nullable=True),
    sa.Column('yds', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('yds_g', sa.Float(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('lng', sa.String(), nullable=True),
    sa.Column('first', sa.Integer(), nullable=True),
    sa.Column('first_percent', sa.Float(), nullable=True),
    sa.Column('twenty_plus', sa.Integer(), nullable=True),
    sa.Column('forty_plus', sa.Integer(), nullable=True),
    sa.Column('fum', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rushing_stats_id'), 'rushing_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rushing_stats_id'), table_name='rushing_stats')
    op.drop_table('rushing_stats')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_team_short_name'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_position_short_name'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
